CREATE TABLE ADDRESS (
	ID_addr			INTEGER NOT NULL,
	City			VARCHAR2 (40 CHAR) NOT NULL,
	Street			VARCHAR2 (40 CHAR) NOT NULL,
	Building_number	INTEGER,
	Flat_number		INTEGER,
	
	PRIMARY KEY (ID_addr)
);

CREATE TABLE POSITION (
	Name_of_position VARCHAR2 (40 CHAR) NOT NULL,
	
	PRIMARY KEY (Name_of_position)
);

CREATE TABLE POSITION_DATA (
	Name_of_position	VARCHAR2 (40 CHAR) NOT NULL,
	Starting_date		DATE NOT NULL,
	Finish_date			DATE NOT NULL,
	Basic_salary		REAL NOT NULL,
	Overtime			REAL NOT NULL,
	
	PRIMARY KEY (Name_of_position, Starting_date, Finish_date),
	FOREIGN KEY (Name_of_position) REFERENCES POSITION (Name_of_position) NOT DEFERRABLE
);

CREATE TABLE PERSON (
	Pesel		VARCHAR2 (11 CHAR) NOT NULL,
	Surname		VARCHAR2 (40 CHAR) NOT NULL,
	Name		VARCHAR2 (40 CHAR) NOT NULL,
	Birthday	DATE NOT NULL,
	ID_addr		INTEGER NOT NULL,
	
	PRIMARY KEY (Pesel),
	FOREIGN KEY (ID_addr) REFERENCES ADDRESS (ID_addr) NOT DEFERRABLE
);

CREATE TABLE EMPLOYEE (
	ID_emp				INTEGER NOT NULL,
	Pesel				VARCHAR2 (11 CHAR) NOT NULL,
	Employment_date		DATE NOT NULL,
	Name_of_position	VARCHAR2 (40 CHAR) NOT NULL,
	Starting_time		SMALLINT DEFAULT 7 NOT NULL CHECK(Starting_time >= 0 AND Starting_time <=23),
	Salary				REAL NOT NULL,
	
	UNIQUE (Pesel),
	PRIMARY KEY (ID_emp),
	FOREIGN KEY (Pesel) REFERENCES PERSON (Pesel) NOT DEFERRABLE,
	FOREIGN KEY (Name_of_position) REFERENCES POSITION (Name_of_position) NOT DEFERRABLE
);

CREATE TABLE TRAINEE (
	ID_trn			INTEGER NOT NULL,
	Pesel			VARCHAR2 (11 CHAR) NOT NULL,
	Starting_date	DATE NOT NULL,
	Age				INTEGER NOT NULL,
	Theory			BOOLEAN NOT NULL, -- !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	Internal_exam	BOOLEAN NOT NULL, -- !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	
	UNIQUE (Pesel),
	PRIMARY KEY (ID_trn),
	FOREIGN KEY (Pesel) REFERENCES PERSON (Pesel) NOT DEFERRABLE
);

CREATE TABLE WORD (
	ID_word		INTEGER NOT NULL,
	Name		VARCHAR2 (40 CHAR) NOT NULL,
	ID_addr		INTEGER NOT NULL,
	
	UNIQUE (Name),
	UNIQUE (ID_addr),
	PRIMARY KEY (ID_word),
	FOREIGN KEY (ID_addr) REFERENCES ADDRESS (ID_addr) NOT DEFERRABLE
);

CREATE TABLE EXAM_TYPE (
	E_type	VARCHAR2(10 CHAR) NOT NULL,
	Price	REAL NOT NULL,
	
	PRIMARY KEY (E_type)
);

CREATE TABLE EXAM (
	ID_exam		INTEGER NOT NULL,
	E_date		DATE NOT NULL,
	ID_word		INTEGER NOT NULL,
	ID_trn		INTEGER NOT NULL,
	E_type		VARCHAR2 (10 CHAR) NOT NULL,
	Pass_or_not	VARCHAR2 (10 CHAR) DEFAULT 'scheduled' NOT NULL,
	
	PRIMARY KEY (ID_exam),
	FOREIGN KEY (ID_word) REFERENCES WORD (ID_word) NOT DEFERRABLE,
	FOREIGN KEY (ID_trn) REFERENCES TRAINEE (ID_trn) NOT DEFERRABLE,
	FOREIGN KEY (E_type) REFERENCES EXAM_TYPE (E_type) NOT DEFERRABLE
);

CREATE TABLE VEHICLE (
	ID_veh			INTEGER NOT NULL,
	Number_plate	VARCHAR2(9 CHAR) NOT NULL,
	Brand			VARCHAR2(40 CHAR) NOT NULL,
	Model			VARCHAR2(20 CHAR) NOT NULL,
	
	UNIQUE (Number_plate),
	PRIMARY KEY (ID_veh)
);

CREATE TABLE AREA (
	Area_name	VARCHAR2 (20 CHAR) NOT NULL,
	How_long	SMALLINT NOT NULL,
	
	PRIMARY KEY (Area_name)
);

CREATE TABLE LESSON (
	ID_lesson		INTEGER NOT NULL,
	L_date			DATE NOT NULL,
	Starting_time	SMALLINT DEFAULT 7 NOT NULL CHECK(Starting_time >= 0 AND Starting_time <=23),
	Finish_time		SMALLINT NOT NULL CHECK(Finish_time >= 0 AND Finish_time <=23),
	Area_name		VARCHAR2 (20 CHAR) NOT NULL,
	ID_emp			INTEGER NOT NULL,
	ID_trn			INTEGER NOT NULL,
	ID_veh			INTEGER NOT NULL,
	
	PRIMARY KEY (ID_lesson),
	FOREIGN KEY (Area_name) REFERENCES AREA (Area_name) NOT DEFERRABLE,
	FOREIGN KEY (ID_emp) REFERENCES EMPLOYEE (ID_emp) NOT DEFERRABLE,
	FOREIGN KEY (ID_trn) REFERENCES TRAINEE (ID_trn) NOT DEFERRABLE,
	FOREIGN KEY (ID_veh) REFERENCES VEHICLE (ID_veh) NOT DEFERRABLE
);