CREATE SEQUENCE address_ID_addr_seq START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE employee_ID_emp_seq START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE trainee_ID_trn_seq START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE word_ID_word_seq START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE exam_ID_exam_seq START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE vehicle_ID_veh_seq START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE lesson_ID_lesson_seq START WITH 1 NOCACHE ORDER;